import { SettingsType } from '@/types/settings';

export const defaultSettings: SettingsType = {
  theme: 'system',

  units: {
    distance: 'nm',
    speed: 'knots',
    fuel: 'mt',
  },

  currency: 'USD',

  defaults: {
    vessel: '',
    fuelPrice: 650,
    weatherFactor: 1.05,
    safetyMargin: 1.1,
  },

  export: {
    companyName: '',
    reportFooter: 'Generated by Naviscope ETA',
    dateFormat: 'PPpp',
  },
};
