'use client';

import { useForm } from 'react-hook-form';
import FormProvider from '@/components/ui/form/FormProvider';
import Input from '@/components/ui/form/Input';
import SubmitButton from '@/components/ui/form/SubmitButton';
import useButtonState from '@/hooks/useButtonState';

export default function ExportSettings() {
  const methods = useForm({
    defaultValues: {
      companyName: '',
      footer: 'Generated by Naviscope',
    },
  });

  const { handleSubmit } = methods;
  const { state, setLoading, setSuccess } = useButtonState();

  const onSubmit = async () => {
    setLoading();
    await new Promise((r) => setTimeout(r, 800));

    setSuccess();
  };

  return (
    <FormProvider methods={methods}>
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <h2 className="text-lg font-semibold">Export</h2>

        <Input name="companyName" label="Company Name" />
        <Input name="footer" label="Report Footer" />

        <SubmitButton state={state}>Save Export Settings</SubmitButton>
      </form>
    </FormProvider>
  );
}
