'use client';

import { useForm } from 'react-hook-form';

import FormProvider from '@/components/ui/form/FormProvider';
import Input from '@/components/ui/form/Input';
import Select from '@/components/ui/form/Select';
import SubmitButton from '@/components/ui/form/SubmitButton';

import useButtonState from '@/hooks/useButtonState';

const themeOptions = [
  { label: 'System', value: 'system' },
  { label: 'Light', value: 'light' },
  { label: 'Dark', value: 'dark' },
];

const currencyOptions = [
  { label: 'US Dollar (USD)', value: 'USD' },
  { label: 'Euro (EUR)', value: 'EUR' },
  { label: 'British Pound (GBP)', value: 'GBP' },
  { label: 'Nigerian Naira (NGN)', value: 'NGN' },
];

const distanceOptions = [
  { label: 'Nautical Miles', value: 'nm' },
  { label: 'Kilometres', value: 'km' },
];

const speedOptions = [
  { label: 'Knots', value: 'knots' },
  { label: 'km/h', value: 'kmh' },
];

const vesselOptions = [
  { label: 'Container Ship', value: 'container' },
  { label: 'Bulk Carrier', value: 'bulk' },
  { label: 'Oil Tanker', value: 'oil_tanker' },
  { label: 'General Cargo', value: 'general_cargo' },
];

type SettingsFormValues = {
  theme: string;

  currency: string;

  distanceUnit: string;

  speedUnit: string;

  defaultVessel: string;

  fuelPrice: string;

  weatherFactor: string;

  safetyMargin: string;

  companyName: string;

  reportFooter: string;
};

export default function SettingsForm() {
  const methods = useForm<SettingsFormValues>({
    mode: 'onChange',

    defaultValues: {
      theme: 'system',

      currency: 'USD',

      distanceUnit: 'nm',

      speedUnit: 'knots',

      defaultVessel: 'container',

      fuelPrice: '650',

      weatherFactor: '1.05',

      safetyMargin: '1.10',

      companyName: '',

      reportFooter: 'Generated by Naviscope ETA',
    },
  });

  const { handleSubmit } = methods;

  const { state, setLoading, setSuccess, setError } = useButtonState();

  const onSubmit = async () => {
    try {
      setLoading();

      await new Promise((resolve) => setTimeout(resolve, 1200));

      // Save to localStorage/API here

      setSuccess();
    } catch {
      setError();
    }
  };

  return (
    <FormProvider methods={methods}>
      <form
        onSubmit={handleSubmit(onSubmit)}
        className="space-y-8 rounded-xl border border-border bg-surface p-6"
      >
        {/* Preferences */}

        <section className="space-y-4">
          <h2 className="text-lg font-semibold">Preferences</h2>

          <Select name="theme" label="Theme" options={themeOptions} />

          <Select name="currency" label="Currency" options={currencyOptions} />

          <Select
            name="distanceUnit"
            label="Distance Unit"
            options={distanceOptions}
          />

          <Select name="speedUnit" label="Speed Unit" options={speedOptions} />
        </section>

        {/* Calculation Defaults */}

        <section className="space-y-4">
          <h2 className="text-lg font-semibold">Calculation Defaults</h2>

          <Select
            name="defaultVessel"
            label="Default Vessel"
            options={vesselOptions}
          />

          <Input
            name="fuelPrice"
            label="Default Fuel Price"
            numeric
            inputMode="decimal"
          />

          <Input
            name="weatherFactor"
            label="Weather Factor"
            numeric
            inputMode="decimal"
          />

          <Input
            name="safetyMargin"
            label="Safety Margin"
            numeric
            inputMode="decimal"
          />
        </section>

        {/* Export */}

        <section className="space-y-4">
          <h2 className="text-lg font-semibold">Export</h2>

          <Input name="companyName" label="Company Name" />

          <Input name="reportFooter" label="Report Footer" />
        </section>

        <SubmitButton
          state={state}
          loadingText="Saving"
          successText="Saved"
          errorText="Failed"
        >
          Save Settings
        </SubmitButton>
      </form>
    </FormProvider>
  );
}
